// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AssignProfile(arg1, arg2) {
  return window['go']['main']['App']['AssignProfile'](arg1, arg2);
}

export function CancelNewSSOProfile() {
  return window['go']['main']['App']['CancelNewSSOProfile']();
}

export function FinishNewSSOProfile(arg1, arg2, arg3) {
  return window['go']['main']['App']['FinishNewSSOProfile'](arg1, arg2, arg3);
}

export function ListSSOProfiles() {
  return window['go']['main']['App']['ListSSOProfiles']();
}

export function ListSSORoles(arg1) {
  return window['go']['main']['App']['ListSSORoles'](arg1);
}

export function ListServices() {
  return window['go']['main']['App']['ListServices']();
}

export function LoginSSO(arg1) {
  return window['go']['main']['App']['LoginSSO'](arg1);
}

export function LogoutSSO() {
  return window['go']['main']['App']['LogoutSSO']();
}

export function StartNewSSOProfile(arg1, arg2) {
  return window['go']['main']['App']['StartNewSSOProfile'](arg1, arg2);
}

export function StartService(arg1) {
  return window['go']['main']['App']['StartService'](arg1);
}

export function StopService(arg1) {
  return window['go']['main']['App']['StopService'](arg1);
}
