// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {ssologin} from '../models';

export function AssignProfile(arg1:string,arg2:string):Promise<void>;

export function CancelNewSSOProfile():Promise<void>;

export function FinishNewSSOProfile(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ListSSOProfiles():Promise<Array<main.SSOProfileView>>;

export function ListSSORoles(arg1:string):Promise<Array<ssologin.Role>>;

export function ListServices():Promise<Array<main.ServiceView>>;

export function LoginSSO(arg1:string):Promise<void>;

export function LogoutSSO():Promise<void>;

export function StartNewSSOProfile(arg1:string,arg2:string):Promise<main.DeviceAuthView>;

export function StartService(arg1:string):Promise<void>;

export function StopService(arg1:string):Promise<void>;
